// <auto-generated />
using System;
using Ashraak.Cctv.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ashraak.Cctv.Service.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cctv_service")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Schedule.EngineerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ServiceScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId")
                        .HasDatabaseName("ix_engineer_assignments_engineer_id");

                    b.HasIndex("ServiceScheduleId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_engineer_assignments_schedule_active")
                        .HasFilter("is_active = true");

                    b.ToTable("engineer_assignments", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AmcContractTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_contract_term_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_generated");

                    b.Property<DateOnly?>("RescheduledFrom")
                        .HasColumnType("date")
                        .HasColumnName("rescheduled_from");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("ScheduleNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schedule_number");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<int>("SequenceInTerm")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_in_term");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_service_schedules_schedule_number");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("ix_service_schedules_scheduled_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_schedules_status");

                    b.ToTable("service_schedules", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<bool>("IsCustomerVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer_visible");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("report_status");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ServiceScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_schedule_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VisitRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("visit_remarks");

                    b.HasKey("Id");

                    b.HasIndex("ServiceScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ux_service_visits_service_schedule_id");

                    b.ToTable("service_visits", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<string>("ReviewRemarks")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_remarks");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<Guid>("ServiceVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_visit_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId");

                    b.ToTable("visit_approvals", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("attachment_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("ServiceVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_visit_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId");

                    b.ToTable("visit_attachments", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<Guid>("ServiceVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_visit_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_locations_service_visit_id");

                    b.ToTable("visit_locations", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("ServiceVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_visit_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId");

                    b.ToTable("visit_photos", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("ServiceVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_visit_id");

                    b.Property<string>("SignedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("signed_by_name");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_signatures_service_visit_id");

                    b.ToTable("visit_signatures", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "cctv_service");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Schedule.EngineerAssignment", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ServiceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitApproval", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", null)
                        .WithMany("Approvals")
                        .HasForeignKey("ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitAttachment", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitLocation", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", null)
                        .WithOne("Location")
                        .HasForeignKey("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitLocation", "ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitPhoto", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", null)
                        .WithMany("Photos")
                        .HasForeignKey("ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitSignature", b =>
                {
                    b.HasOne("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", null)
                        .WithOne("Signature")
                        .HasForeignKey("Ashraak.Cctv.Service.Domain.Aggregates.Visit.VisitSignature", "ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Attachments");

                    b.Navigation("Location");

                    b.Navigation("Photos");

                    b.Navigation("Signature");
                });
#pragma warning restore 612, 618
        }
    }
}
