using Ashraak.Cctv.Service.Domain.Aggregates.Schedule;
using Ashraak.Cctv.Service.Domain.Aggregates.Visit;
using Ashraak.Cctv.Service.Domain.Enums;
using FluentAssertions;
using Xunit;
using ScheduleAggregate = Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule;
using VisitAggregate = Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit;

namespace Ashraak.Integration.Tests.Cctv;

/// <summary>D1-5 domain tests for service schedules and visits.</summary>
public sealed class ServiceDomainTests
{
    private static readonly Guid TestUserId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    [Fact]
    public void AssignEngineer_MovesScheduleToAssigned()
    {
        var schedule = CreatePlannedSchedule();
        schedule.AssignEngineer(Guid.NewGuid(), TestUserId);
        schedule.Status.Should().Be(ScheduleStatus.Assigned);
        schedule.ActiveAssignment.Should().NotBeNull();
    }

    [Fact]
    public void MarkInProgress_RequiresActiveAssignment()
    {
        var schedule = CreatePlannedSchedule();
        var act = () => schedule.MarkInProgress(TestUserId);
        act.Should().Throw<InvalidOperationException>().WithMessage("*engineer*");
    }

    [Fact]
    public void MarkInProgress_SucceedsWhenEngineerAssigned()
    {
        var schedule = CreatePlannedSchedule();
        schedule.AssignEngineer(Guid.NewGuid(), TestUserId);
        schedule.MarkInProgress(TestUserId);
        schedule.Status.Should().Be(ScheduleStatus.InProgress);
    }

    [Fact]
    public void Reschedule_ReasonMustBeAtLeastTenCharacters()
    {
        var schedule = CreatePlannedSchedule();
        var act = () => schedule.Reschedule(DateOnly.FromDateTime(DateTime.UtcNow.AddDays(7)), "short", TestUserId);
        act.Should().Throw<InvalidOperationException>().WithMessage("*10*");
    }

    [Fact]
    public void Reschedule_WithValidReason_UpdatesDate()
    {
        var schedule = CreatePlannedSchedule();
        var newDate = schedule.ScheduledDate.AddDays(14);
        schedule.Reschedule(newDate, "Customer requested later slot", TestUserId);
        schedule.ScheduledDate.Should().Be(newDate);
        schedule.RescheduledFrom.Should().NotBeNull();
    }

    [Fact]
    public void Cancel_RequiresReason()
    {
        var schedule = CreatePlannedSchedule();
        var act = () => schedule.Cancel(string.Empty, TestUserId);
        act.Should().Throw<InvalidOperationException>().WithMessage("*reason*");
    }

    [Fact]
    public void SubmitReport_FailsWhenEvidenceMissing()
    {
        var scheduleId = ServiceScheduleId.New();
        var visit = VisitAggregate.CreateDraft(ServiceVisitId.New(), scheduleId, Guid.NewGuid(), TestUserId);
        visit.Start(DateTime.UtcNow, TestUserId);
        visit.UpdateRemarks("These remarks are long enough for submit.", TestUserId);

        var act = () => visit.SubmitReport(TestUserId);
        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void SubmitReport_SucceedsWhenAllEvidencePresent()
    {
        var scheduleId = ServiceScheduleId.New();
        var visit = VisitAggregate.CreateDraft(ServiceVisitId.New(), scheduleId, Guid.NewGuid(), TestUserId);
        visit.Start(DateTime.UtcNow, TestUserId);
        visit.LinkSelfie(Guid.NewGuid(), DateTime.UtcNow, TestUserId);
        visit.LinkPhoto(Guid.NewGuid(), VisitPhotoCategory.Before, null, DateTime.UtcNow, TestUserId);
        visit.CaptureLocation(12.9716m, 77.5946m, DateTime.UtcNow, TestUserId);
        visit.LinkSignature(Guid.NewGuid(), "Site Contact", DateTime.UtcNow, TestUserId);
        visit.UpdateRemarks("Completed preventive maintenance with full checklist.", TestUserId);

        visit.SubmitReport(TestUserId);
        visit.ReportStatus.Should().Be(VisitReportStatus.Submitted);
    }

    [Fact]
    public void Approve_SetsCustomerVisible()
    {
        var scheduleId = ServiceScheduleId.New();
        var siteId = Guid.NewGuid();
        var visit = BuildSubmittedVisit(scheduleId);
        visit.Approve(TestUserId, "Looks good", siteId);
        visit.IsCustomerVisible.Should().BeTrue();
        visit.ReportStatus.Should().Be(VisitReportStatus.Approved);
    }

    private static ScheduleAggregate CreatePlannedSchedule()
    {
        return ServiceSchedule.CreateAutoGenerated(
            ServiceScheduleId.New(),
            "VS-2026-0001",
            Guid.NewGuid(),
            Guid.NewGuid(),
            DateOnly.FromDateTime(DateTime.UtcNow.AddDays(7)),
            1,
            TestUserId);
    }

    private static VisitAggregate BuildSubmittedVisit(ServiceScheduleId scheduleId)
    {
        var visit = VisitAggregate.CreateDraft(ServiceVisitId.New(), scheduleId, Guid.NewGuid(), TestUserId);
        visit.Start(DateTime.UtcNow, TestUserId);
        visit.LinkSelfie(Guid.NewGuid(), DateTime.UtcNow, TestUserId);
        visit.LinkPhoto(Guid.NewGuid(), VisitPhotoCategory.After, null, DateTime.UtcNow, TestUserId);
        visit.CaptureLocation(12.9716m, 77.5946m, DateTime.UtcNow, TestUserId);
        visit.LinkSignature(Guid.NewGuid(), "Site Contact", DateTime.UtcNow, TestUserId);
        visit.UpdateRemarks("Completed preventive maintenance with full checklist.", TestUserId);
        visit.SubmitReport(TestUserId);
        return visit;
    }
}
