// <auto-generated />
using System;
using Ashraak.Cctv.Amc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ashraak.Cctv.Amc.Infrastructure.Migrations
{
    [DbContext(typeof(AmcDbContext))]
    [Migration("20260611142753_InitialAmcSchema")]
    partial class InitialAmcSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cctv_amc")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_contracts_contract_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_amc_contracts_customer_id");

                    b.HasIndex("SiteId")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_contracts_site_id_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_amc_contracts_status");

                    b.ToTable("amc_contracts", "cctv_amc");
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_contract_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_contract_term_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_amc_contract_documents_contract_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_amc_contract_documents_file_id");

                    b.ToTable("amc_contract_documents", "cctv_amc");
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContractTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgreedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agreed_price");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_contract_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_plan_version_id");

                    b.Property<DateTime?>("RenewalRequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewal_requested_at");

                    b.Property<bool>("RenewalRequestedByCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("renewal_requested_by_customer");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TermNo")
                        .HasColumnType("integer")
                        .HasColumnName("term_no");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_contract_terms_contract_id_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_amc_contract_terms_end_date");

                    b.HasIndex("ContractId", "TermNo")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_contract_terms_contract_id_term_no");

                    b.ToTable("amc_contract_terms", "cctv_amc", t =>
                        {
                            t.HasCheckConstraint("ck_amc_contract_terms_dates", "end_date > start_date");
                        });
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Plan.AmcPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan_code");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_plans_plan_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_amc_plans_status");

                    b.ToTable("amc_plans", "cctv_amc");
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Plan.AmcPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("IncludedServicesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("included_services");

                    b.Property<bool>("IsReferenced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_referenced");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("amc_plan_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("SlaTerms")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("sla_terms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.Property<int>("VisitFrequencyPerYear")
                        .HasColumnType("integer")
                        .HasColumnName("visit_frequency_per_year");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_amc_plan_versions_plan_id_version_no");

                    b.ToTable("amc_plan_versions", "cctv_amc");
                });

            modelBuilder.Entity("Ashraak.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "cctv_amc");
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContractDocument", b =>
                {
                    b.HasOne("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContract", null)
                        .WithMany("Documents")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContractTerm", b =>
                {
                    b.HasOne("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContract", null)
                        .WithMany("Terms")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Plan.AmcPlanVersion", b =>
                {
                    b.HasOne("Ashraak.Cctv.Amc.Domain.Aggregates.Plan.AmcPlan", null)
                        .WithMany("Versions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Contract.AmcContract", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Ashraak.Cctv.Amc.Domain.Aggregates.Plan.AmcPlan", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
