namespace Ashraak.SharedKernel.Contracts.CctvCrm.Dtos;

/// <summary>Schedule detail (GET /cctv/schedules/{id}).</summary>
public sealed record ScheduleDetailDto(
    Guid Id,
    string ScheduleNumber,
    Guid SiteId,
    Guid? AmcContractTermId,
    DateOnly ScheduledDate,
    int SequenceInTerm,
    string Status,
    DateOnly? RescheduledFrom,
    bool IsAutoGenerated,
    DateTime CreatedAtUtc,
    Guid CreatedBy,
    DateTime? UpdatedAtUtc,
    Guid? UpdatedBy,
    uint RowVersion,
    EngineerAssignmentDto? ActiveAssignment,
    IReadOnlyList<EngineerAssignmentDto> AssignmentHistory,
    VisitSummaryDto? Visit);
