namespace Ashraak.SharedKernel.Contracts.CctvCrm.Dtos;

/// <summary>Schedule list row (GET /cctv/schedules).</summary>
public sealed record ScheduleSummaryDto(
    Guid Id,
    string ScheduleNumber,
    Guid SiteId,
    Guid? AmcContractTermId,
    DateOnly ScheduledDate,
    int SequenceInTerm,
    string Status,
    Guid? ActiveEngineerId,
    Guid? VisitId,
    bool IsAutoGenerated,
    DateTime CreatedAtUtc);
