using Ashraak.Cctv.Service.Application.Abstractions;
using Ashraak.Cctv.Service.Domain.Aggregates.Schedule;
using Ashraak.Cctv.Service.Domain.Repositories;
using Ashraak.SharedKernel.Contracts.CctvCrm.Interfaces;
using Ashraak.SharedKernel.Interfaces;

namespace Ashraak.Cctv.Service.Infrastructure.Services;

internal sealed class ScheduleGenerationService(
    IAmcContractLookupService amcContractLookup,
    IServiceScheduleRepository scheduleRepository,
    IServiceScheduleNumberGenerator numberGenerator,
    IUnitOfWork unitOfWork) : IScheduleGenerationService
{
    public async Task GenerateSchedulesForTermAsync(
        Guid contractId,
        Guid termId,
        Guid activatedBy,
        CancellationToken cancellationToken = default)
    {
        var term = await amcContractLookup.GetTermByIdAsync(contractId, termId, cancellationToken);
        if (term is null)
            return;

        if (term.Status != "Active")
            return;

        var existing = await scheduleRepository.CountByTermAsync(termId, cancellationToken);
        if (existing > 0)
            return;

        var frequency = term.VisitFrequencyPerYear;
        if (frequency <= 0)
            return;

        var contract = await amcContractLookup.GetByIdAsync(contractId, cancellationToken);
        if (contract is null)
            return;

        var schedules = new List<ServiceSchedule>();
        var totalDays = term.EndDate.DayNumber - term.StartDate.DayNumber + 1;
        if (totalDays <= 0)
            return;

        var interval = Math.Max(1, totalDays / frequency);

        for (var i = 0; i < frequency; i++)
        {
            var offsetDays = i * interval;
            if (offsetDays >= totalDays)
                offsetDays = totalDays - 1;

            var scheduledDate = term.StartDate.AddDays(offsetDays);
            if (scheduledDate > term.EndDate)
                scheduledDate = term.EndDate;

            var scheduleNumber = await numberGenerator.GenerateNextAsync(cancellationToken);
            var schedule = ServiceSchedule.CreateAutoGenerated(
                ServiceScheduleId.New(),
                scheduleNumber,
                termId,
                contract.SiteId,
                scheduledDate,
                i + 1,
                activatedBy);

            schedules.Add(schedule);
        }

        scheduleRepository.AddRange(schedules);
        await unitOfWork.SaveChangesAsync(cancellationToken);
    }
}
