// <auto-generated />
using System;
using Ashraak.Cctv.Customer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ashraak.Cctv.Customer.Infrastructure.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260611135233_AddSiteTables")]
    partial class AddSiteTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cctv_customer")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Customer.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("billing_address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("PortalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("portal_user_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_customers_created_at");

                    b.HasIndex("CustomerNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_customer_number");

                    b.HasIndex("PortalUserId")
                        .HasDatabaseName("ix_customers_portal_user_id");

                    b.HasIndex("SourceLeadId")
                        .HasDatabaseName("ix_customers_source_lead_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_customers_status");

                    b.ToTable("customers", "cctv_customer");
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("site_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_sites_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sites_customer_id");

                    b.HasIndex("SiteNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sites_site_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sites_status");

                    b.ToTable("sites", "cctv_customer");
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteAssetSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<int>("CameraCount")
                        .HasColumnType("integer")
                        .HasColumnName("camera_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DvrCount")
                        .HasColumnType("integer")
                        .HasColumnName("dvr_count");

                    b.Property<int>("HardDiskCount")
                        .HasColumnType("integer")
                        .HasColumnName("hard_disk_count");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int>("MonitorCount")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_count");

                    b.Property<int>("NvrCount")
                        .HasColumnType("integer")
                        .HasColumnName("nvr_count");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remarks");

                    b.Property<int>("RouterCount")
                        .HasColumnType("integer")
                        .HasColumnName("router_count");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("SwitchCount")
                        .HasColumnType("integer")
                        .HasColumnName("switch_count");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique()
                        .HasDatabaseName("ux_site_asset_summaries_site_id");

                    b.ToTable("site_asset_summaries", "cctv_customer", t =>
                        {
                            t.HasCheckConstraint("ck_site_asset_summaries_counts_non_negative", "camera_count >= 0 AND dvr_count >= 0 AND nvr_count >= 0 AND hard_disk_count >= 0 AND switch_count >= 0 AND router_count >= 0 AND monitor_count >= 0");
                        });
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("ContactSlot")
                        .HasColumnType("smallint")
                        .HasColumnName("contact_slot");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "ContactSlot")
                        .IsUnique()
                        .HasDatabaseName("ux_site_contacts_site_id_contact_slot");

                    b.ToTable("site_contacts", "cctv_customer", t =>
                        {
                            t.HasCheckConstraint("ck_site_contacts_contact_slot", "contact_slot >= 1 AND contact_slot <= 3");
                        });
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_documents_site_id");

                    b.ToTable("site_documents", "cctv_customer");
                });

            modelBuilder.Entity("Ashraak.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "cctv_customer");
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteAssetSummary", b =>
                {
                    b.HasOne("Ashraak.Cctv.Customer.Domain.Aggregates.Site.Site", null)
                        .WithOne("AssetSummary")
                        .HasForeignKey("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteAssetSummary", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteContact", b =>
                {
                    b.HasOne("Ashraak.Cctv.Customer.Domain.Aggregates.Site.Site", null)
                        .WithMany("Contacts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.SiteDocument", b =>
                {
                    b.HasOne("Ashraak.Cctv.Customer.Domain.Aggregates.Site.Site", null)
                        .WithMany("Documents")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashraak.Cctv.Customer.Domain.Aggregates.Site.Site", b =>
                {
                    b.Navigation("AssetSummary");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
