import { apiClient } from '@/core/api/client';
import { ENDPOINTS } from '@/core/api/endpoints';
import type { PagedSchedules, ScheduleDetail, ScheduleListFilters, ScheduleSummary } from './types';

function str(raw: Record<string, unknown>, camel: string, pascal: string): string {
  return String(raw[camel] ?? raw[pascal] ?? '');
}

function num(raw: Record<string, unknown>, camel: string, pascal: string): number {
  return Number(raw[camel] ?? raw[pascal] ?? 0);
}

function mapScheduleSummary(raw: Record<string, unknown>): ScheduleSummary {
  return {
    id: str(raw, 'id', 'Id'),
    scheduleNumber: str(raw, 'scheduleNumber', 'ScheduleNumber'),
    siteId: str(raw, 'siteId', 'SiteId'),
    amcContractTermId: (raw.amcContractTermId ?? raw.AmcContractTermId ?? null) as string | null,
    scheduledDate: str(raw, 'scheduledDate', 'ScheduledDate'),
    sequenceInTerm: num(raw, 'sequenceInTerm', 'SequenceInTerm'),
    status: str(raw, 'status', 'Status') as ScheduleSummary['status'],
    activeEngineerId: (raw.activeEngineerId ?? raw.ActiveEngineerId ?? null) as string | null,
    visitId: (raw.visitId ?? raw.VisitId ?? null) as string | null,
    isAutoGenerated: Boolean(raw.isAutoGenerated ?? raw.IsAutoGenerated),
    createdAtUtc: str(raw, 'createdAtUtc', 'CreatedAtUtc'),
  };
}

function mapScheduleDetail(raw: Record<string, unknown>): ScheduleDetail {
  const summary = mapScheduleSummary(raw);
  return {
    ...summary,
    rescheduledFrom: (raw.rescheduledFrom ?? raw.RescheduledFrom ?? null) as string | null,
    createdBy: str(raw, 'createdBy', 'CreatedBy'),
    updatedAtUtc: (raw.updatedAtUtc ?? raw.UpdatedAtUtc ?? null) as string | null,
    updatedBy: (raw.updatedBy ?? raw.UpdatedBy ?? null) as string | null,
    rowVersion: num(raw, 'rowVersion', 'RowVersion'),
  };
}

function mapPagedSchedules(raw: Record<string, unknown>): PagedSchedules {
  const itemsRaw = (raw.items ?? raw.Items ?? []) as unknown[];
  return {
    items: itemsRaw.map((item) => mapScheduleSummary(item as Record<string, unknown>)),
    page: num(raw, 'page', 'Page') || num(raw, 'pageNumber', 'PageNumber') || 1,
    pageSize: num(raw, 'pageSize', 'PageSize') || 20,
    totalCount: num(raw, 'totalCount', 'TotalCount'),
    totalPages: num(raw, 'totalPages', 'TotalPages') || 1,
    hasNextPage: Boolean(raw.hasNextPage ?? raw.HasNextPage),
    hasPreviousPage: Boolean(raw.hasPreviousPage ?? raw.HasPreviousPage),
  };
}

export const schedulesApi = {
  list: async (filters: ScheduleListFilters = {}): Promise<PagedSchedules> => {
    const params = new URLSearchParams();
    if (filters.page) params.set('page', String(filters.page));
    if (filters.pageSize) params.set('pageSize', String(filters.pageSize));
    if (filters.status) params.set('status', filters.status);
    if (filters.fromDate) params.set('fromDate', filters.fromDate);
    if (filters.toDate) params.set('toDate', filters.toDate);
    const qs = params.toString();
    const url = qs ? `${ENDPOINTS.cctv.schedules.list}?${qs}` : ENDPOINTS.cctv.schedules.list;
    const res = await apiClient.get<Record<string, unknown>>(url);
    return mapPagedSchedules(res.data);
  },

  get: async (id: string): Promise<ScheduleDetail> => {
    const res = await apiClient.get<Record<string, unknown>>(ENDPOINTS.cctv.schedules.byId(id));
    return mapScheduleDetail(res.data);
  },
};
