export type ScheduleStatus =
  | 'Planned'
  | 'Assigned'
  | 'InProgress'
  | 'Completed'
  | 'Missed'
  | 'Cancelled';

export interface ScheduleSummary {
  readonly id: string;
  readonly scheduleNumber: string;
  readonly siteId: string;
  readonly amcContractTermId: string | null;
  readonly scheduledDate: string;
  readonly sequenceInTerm: number;
  readonly status: ScheduleStatus;
  readonly activeEngineerId: string | null;
  readonly visitId: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAtUtc: string;
}

export interface ScheduleDetail extends ScheduleSummary {
  readonly rescheduledFrom: string | null;
  readonly createdBy: string;
  readonly updatedAtUtc: string | null;
  readonly updatedBy: string | null;
  readonly rowVersion: number;
}

export interface ScheduleListFilters {
  readonly page?: number;
  readonly pageSize?: number;
  readonly status?: ScheduleStatus;
  readonly fromDate?: string;
  readonly toDate?: string;
}

export interface PagedSchedules {
  readonly items: readonly ScheduleSummary[];
  readonly page: number;
  readonly pageSize: number;
  readonly totalCount: number;
  readonly totalPages: number;
  readonly hasNextPage: boolean;
  readonly hasPreviousPage: boolean;
}
