using Ashraak.Cctv.Service.Domain.Aggregates.Schedule;
using Ashraak.Cctv.Service.Domain.Aggregates.Visit;
using Ashraak.Cctv.Service.Domain.Enums;
using Ashraak.SharedKernel.Contracts.CctvCrm.Dtos;
using ScheduleAggregate = Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule;
using VisitAggregate = Ashraak.Cctv.Service.Domain.Aggregates.Visit.ServiceVisit;

namespace Ashraak.Cctv.Service.Application.Mapping;

internal static class ServiceMapper
{
    public static ScheduleSummaryDto ToScheduleSummary(ScheduleAggregate schedule, VisitAggregate? visit)
    {
        var active = schedule.ActiveAssignment;
        return new ScheduleSummaryDto(
            schedule.Id.Value,
            schedule.ScheduleNumber,
            schedule.SiteId,
            schedule.AmcContractTermId,
            schedule.ScheduledDate,
            schedule.SequenceInTerm,
            schedule.Status.ToString(),
            active?.EngineerId,
            visit?.Id.Value,
            schedule.IsAutoGenerated,
            schedule.CreatedAtUtc);
    }

    public static ScheduleDetailDto ToScheduleDetail(ScheduleAggregate schedule, VisitAggregate? visit)
    {
        var active = schedule.ActiveAssignment;
        var history = schedule.Assignments
            .OrderByDescending(a => a.AssignedAtUtc)
            .Select(ToAssignmentDto)
            .ToList();

        return new ScheduleDetailDto(
            schedule.Id.Value,
            schedule.ScheduleNumber,
            schedule.SiteId,
            schedule.AmcContractTermId,
            schedule.ScheduledDate,
            schedule.SequenceInTerm,
            schedule.Status.ToString(),
            schedule.RescheduledFrom,
            schedule.IsAutoGenerated,
            schedule.CreatedAtUtc,
            schedule.CreatedBy,
            schedule.UpdatedAtUtc,
            schedule.UpdatedBy,
            schedule.RowVersion,
            active is null ? null : ToAssignmentDto(active),
            history,
            visit is null ? null : ToVisitSummary(visit, schedule));
    }

    public static EngineerAssignmentDto ToAssignmentDto(EngineerAssignment assignment) =>
        new(
            assignment.Id,
            assignment.EngineerId,
            assignment.AssignedBy,
            assignment.AssignedAtUtc,
            assignment.IsActive);

    public static VisitSummaryDto ToVisitSummary(VisitAggregate visit, ScheduleAggregate schedule) =>
        new(
            visit.Id.Value,
            schedule.Id.Value,
            schedule.ScheduleNumber,
            schedule.SiteId,
            visit.EngineerId,
            visit.ReportStatus.ToString(),
            visit.StartedAtUtc,
            visit.CompletedAtUtc,
            visit.IsCustomerVisible,
            visit.CreatedAtUtc);

    public static VisitDetailDto ToVisitDetail(VisitAggregate visit, ScheduleAggregate schedule) =>
        new(
            visit.Id.Value,
            schedule.Id.Value,
            schedule.ScheduleNumber,
            schedule.SiteId,
            visit.EngineerId,
            visit.StartedAtUtc,
            visit.CompletedAtUtc,
            visit.VisitRemarks,
            visit.ReportStatus.ToString(),
            visit.IsCustomerVisible,
            visit.CreatedAtUtc,
            visit.CreatedBy,
            visit.UpdatedAtUtc,
            visit.UpdatedBy,
            visit.RowVersion,
            visit.HasSelfie,
            visit.HasGps,
            visit.HasBeforeDuringAfterPhoto,
            visit.HasSignature,
            visit.HasMinimumRemarks,
            visit.Photos.Select(ToPhotoDto).ToList(),
            visit.Location is null ? null : ToLocationDto(visit.Location),
            visit.Signature is null ? null : ToSignatureDto(visit.Signature),
            visit.Approvals.Select(ToApprovalDto).ToList(),
            visit.Attachments.Select(ToAttachmentDto).ToList());

    public static VisitPhotoDto ToPhotoDto(VisitPhoto photo) =>
        new(photo.Id, photo.FileId, photo.Category.ToString(), photo.Caption, photo.CapturedAtUtc, photo.CreatedAtUtc, photo.CreatedBy);

    public static VisitLocationDto ToLocationDto(VisitLocation location) =>
        new(location.Id, location.Latitude, location.Longitude, location.CapturedAtUtc, location.CreatedAtUtc, location.CreatedBy);

    public static VisitSignatureDto ToSignatureDto(VisitSignature signature) =>
        new(signature.Id, signature.FileId, signature.SignedByName, signature.CapturedAtUtc, signature.CreatedAtUtc, signature.CreatedBy);

    public static VisitApprovalDto ToApprovalDto(VisitApproval approval) =>
        new(approval.Id, approval.Decision.ToString(), approval.ReviewedBy, approval.ReviewedAtUtc, approval.ReviewRemarks, approval.CreatedAtUtc, approval.CreatedBy);

    public static VisitAttachmentDto ToAttachmentDto(VisitAttachment attachment) =>
        new(attachment.Id, attachment.FileId, attachment.AttachmentType.ToString(), attachment.Title, attachment.CreatedAtUtc, attachment.CreatedBy);

    public static bool TryParseScheduleStatus(string? value, out ScheduleStatus status)
    {
        status = default;
        return !string.IsNullOrWhiteSpace(value) && Enum.TryParse(value, true, out status);
    }

    public static bool TryParseVisitReportStatus(string? value, out VisitReportStatus status)
    {
        status = default;
        return !string.IsNullOrWhiteSpace(value) && Enum.TryParse(value, true, out status);
    }

    public static bool TryParsePhotoCategory(string value, out VisitPhotoCategory category)
    {
        category = default;
        return Enum.TryParse(value, true, out category)
            && category is not VisitPhotoCategory.Selfie;
    }

    public static bool TryParseAttachmentType(string value, out VisitAttachmentType attachmentType)
    {
        attachmentType = default;
        return Enum.TryParse(value, true, out attachmentType);
    }
}
