using System.Text.Json;
using Ashraak.Cctv.Integration.Application.Abstractions;
using Microsoft.Extensions.Logging;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Ashraak.Cctv.Integration.Infrastructure.Services;

/// <summary>Production PDF renderer using QuestPDF (ADR-CCTV-0002).</summary>
internal sealed class PdfGenerationService(ILogger<PdfGenerationService> logger) : IPdfGenerationService
{
    static PdfGenerationService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<byte[]> GenerateAsync(string templateKey, object model, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(templateKey);
        ArgumentNullException.ThrowIfNull(model);

        logger.LogInformation("Generating PDF for template {TemplateKey}", templateKey);

        var fields = ToFieldMap(model);
        var document = templateKey.ToLowerInvariant() switch
        {
            "invoice" => BuildInvoiceDocument(fields),
            "contract" => BuildContractDocument(fields),
            "visit" => BuildVisitDocument(fields),
            _ => throw new ArgumentException($"Unknown PDF template key: {templateKey}", nameof(templateKey))
        };

        var bytes = document.GeneratePdf();
        return Task.FromResult(bytes);
    }

    private static Dictionary<string, string> ToFieldMap(object model)
    {
        var json = JsonSerializer.Serialize(model);
        using var doc = JsonDocument.Parse(json);
        return Flatten(doc.RootElement);
    }

    private static Dictionary<string, string> Flatten(JsonElement element, string prefix = "")
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                foreach (var prop in element.EnumerateObject())
                {
                    var key = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";
                    if (prop.Value.ValueKind is JsonValueKind.Object or JsonValueKind.Array)
                        foreach (var (k, v) in Flatten(prop.Value, key))
                            map[k] = v;
                    else
                        map[key] = prop.Value.ToString();
                }
                break;
            case JsonValueKind.Array:
                var index = 0;
                foreach (var item in element.EnumerateArray())
                {
                    foreach (var (k, v) in Flatten(item, $"{prefix}[{index}]"))
                        map[k] = v;
                    index++;
                }
                break;
            default:
                map[prefix] = element.ToString();
                break;
        }
        return map;
    }

    private static string Get(Dictionary<string, string> map, string key, string fallback = "—") =>
        map.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value) ? value : fallback;

    private static Document BuildInvoiceDocument(Dictionary<string, string> f) =>
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Header().Background(Colors.Blue.Darken3).Padding(10).Row(row =>
                {
                    row.RelativeItem().Text("Aarvii Technologies").FontColor(Colors.White).SemiBold().FontSize(18);
                    row.ConstantItem(200).AlignRight().Text("TAX INVOICE").FontColor(Colors.White).FontSize(14);
                });
                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Invoice: {Get(f, "InvoiceNumber")}").SemiBold().FontSize(16);
                    col.Item().PaddingTop(10).Text($"Customer ID: {Get(f, "CustomerId")}");
                    col.Item().Text($"Invoice date: {Get(f, "InvoiceDate")}");
                    col.Item().Text($"Due date: {Get(f, "DueDate")}");
                    col.Item().PaddingTop(10).Text($"Subtotal: {Get(f, "SubtotalAmount")}");
                    col.Item().Text($"Tax: {Get(f, "TaxAmount")}");
                    col.Item().Text($"Total: {Get(f, "TotalAmount")}").SemiBold();
                    col.Item().PaddingTop(16).Text("Line items").SemiBold();
                    col.Item().Text(GetLineItemsSummary(f));
                });
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Aarvii CCTV AMC · ");
                    text.Span(DateTime.UtcNow.ToString("u"));
                });
            });
        });

    private static Document BuildContractDocument(Dictionary<string, string> f) =>
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Header().Background(Colors.Blue.Darken3).Padding(10).Text("AMC Service Contract")
                    .FontColor(Colors.White).SemiBold().FontSize(18);
                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Contract: {Get(f, "ContractNumber")}").SemiBold().FontSize(16);
                    col.Item().PaddingTop(8).Text($"Customer: {Get(f, "CustomerName")}");
                    col.Item().Text($"Site: {Get(f, "SiteName")} — {Get(f, "SiteAddress")}");
                    col.Item().Text($"Plan: {Get(f, "PlanName")} ({Get(f, "PlanCode")})");
                    col.Item().Text($"Coverage: {Get(f, "StartDate")} to {Get(f, "EndDate")}");
                    col.Item().Text($"Visit frequency: {Get(f, "VisitFrequencyPerYear")} visits/year");
                    col.Item().Text($"Agreed price: INR {Get(f, "AgreedPrice")}");
                    col.Item().PaddingTop(12).Text($"SLA: {Get(f, "SlaTerms")}");
                    col.Item().PaddingTop(12).Text($"Included services: {Get(f, "IncludedServices")}");
                    col.Item().PaddingTop(20).Text($"Approved by: {Get(f, "ApprovedBy")} on {Get(f, "ApprovedAtUtc")}");
                });
                page.Footer().AlignCenter().Text("Aarvii Technologies · Confidential");
            });
        });

    private static Document BuildVisitDocument(Dictionary<string, string> f) =>
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Header().Background(Colors.Blue.Darken3).Padding(10).Text("Service Visit Report")
                    .FontColor(Colors.White).SemiBold().FontSize(18);
                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Schedule: {Get(f, "ScheduleNumber")}").SemiBold().FontSize(16);
                    col.Item().PaddingTop(8).Text($"Engineer: {Get(f, "EngineerName")}");
                    col.Item().Text($"Visit date: {Get(f, "VisitDate")}");
                    col.Item().Text($"Status: {Get(f, "ReportStatus")}");
                    col.Item().PaddingTop(12).Text($"GPS: {Get(f, "GpsSummary")}");
                    col.Item().Text($"Evidence: {Get(f, "EvidenceSummary")}");
                    col.Item().PaddingTop(12).Text($"Remarks: {Get(f, "VisitRemarks")}");
                    col.Item().PaddingTop(12).Text($"Approval: {Get(f, "ApprovalStatus")}");
                });
                page.Footer().AlignCenter().Text("Aarvii Technologies · Service Visit Report");
            });
        });

    private static string GetLineItemsSummary(Dictionary<string, string> f)
    {
        var lines = f.Keys
            .Where(k => k.StartsWith("Lines[", StringComparison.Ordinal) && k.EndsWith(".Description", StringComparison.Ordinal))
            .Select(k =>
            {
                var prefix = k[..k.LastIndexOf('.')];
                return $"- {Get(f, $"{prefix}.Description")}: {Get(f, $"{prefix}.LineTotal")}";
            })
            .ToList();
        return lines.Count > 0 ? string.Join(Environment.NewLine, lines) : "No line items";
    }
}
