using Ashraak.Cctv.Service.Domain.Aggregates.Schedule;
using Ashraak.Cctv.Service.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScheduleAggregate = Ashraak.Cctv.Service.Domain.Aggregates.Schedule.ServiceSchedule;

namespace Ashraak.Cctv.Service.Infrastructure.Persistence.Configurations;

internal sealed class ServiceScheduleConfiguration : IEntityTypeConfiguration<ScheduleAggregate>
{
    public void Configure(EntityTypeBuilder<ScheduleAggregate> builder)
    {
        builder.ToTable("service_schedules");
        builder.HasKey(s => s.Id);
        builder.Property(s => s.Id)
            .HasConversion(id => id.Value, value => ServiceScheduleId.From(value))
            .HasColumnName("id");
        builder.Property(s => s.ScheduleNumber).HasMaxLength(32).IsRequired().HasColumnName("schedule_number");
        builder.Property(s => s.AmcContractTermId).HasColumnName("amc_contract_term_id");
        builder.Property(s => s.SiteId).IsRequired().HasColumnName("site_id");
        builder.Property(s => s.ScheduledDate).IsRequired().HasColumnName("scheduled_date");
        builder.Property(s => s.SequenceInTerm).IsRequired().HasColumnName("sequence_in_term");
        builder.Property(s => s.Status).HasConversion<string>().HasMaxLength(32).IsRequired().HasColumnName("status");
        builder.Property(s => s.RescheduledFrom).HasColumnName("rescheduled_from");
        builder.Property(s => s.IsAutoGenerated).IsRequired().HasColumnName("is_auto_generated");
        builder.Property(s => s.CreatedAtUtc).IsRequired().HasColumnName("created_at");
        builder.Property(s => s.CreatedBy).IsRequired().HasColumnName("created_by");
        builder.Property(s => s.UpdatedAtUtc).HasColumnName("updated_at");
        builder.Property(s => s.UpdatedBy).HasColumnName("updated_by");
        builder.Property(s => s.RowVersion).HasColumnName("row_version").IsConcurrencyToken();
        builder.HasIndex(s => s.ScheduleNumber).IsUnique().HasDatabaseName("ux_service_schedules_schedule_number");
        builder.HasIndex(s => s.ScheduledDate).HasDatabaseName("ix_service_schedules_scheduled_date");
        builder.HasIndex(s => s.Status).HasDatabaseName("ix_service_schedules_status");
        builder.HasMany(s => s.Assignments).WithOne().HasForeignKey(a => a.ServiceScheduleId);
        builder.Navigation(s => s.Assignments).UsePropertyAccessMode(PropertyAccessMode.Field);
        builder.Ignore(s => s.ActiveAssignment);
        builder.Ignore(s => s.DomainEvents);
    }
}

internal sealed class EngineerAssignmentConfiguration : IEntityTypeConfiguration<EngineerAssignment>
{
    public void Configure(EntityTypeBuilder<EngineerAssignment> builder)
    {
        builder.ToTable("engineer_assignments");
        builder.HasKey(a => a.Id);
        builder.Property(a => a.Id).HasColumnName("id");
        builder.Property(a => a.ServiceScheduleId)
            .HasConversion(id => id.Value, value => ServiceScheduleId.From(value))
            .HasColumnName("service_schedule_id");
        builder.Property(a => a.EngineerId).IsRequired().HasColumnName("engineer_id");
        builder.Property(a => a.AssignedBy).IsRequired().HasColumnName("assigned_by");
        builder.Property(a => a.AssignedAtUtc).IsRequired().HasColumnName("assigned_at");
        builder.Property(a => a.IsActive).IsRequired().HasColumnName("is_active");
        builder.Property(a => a.CreatedAtUtc).IsRequired().HasColumnName("created_at");
        builder.Property(a => a.CreatedBy).IsRequired().HasColumnName("created_by");
        builder.HasIndex(a => a.EngineerId).HasDatabaseName("ix_engineer_assignments_engineer_id");
        builder.HasIndex(a => new { a.ServiceScheduleId, a.IsActive })
            .IsUnique()
            .HasFilter("is_active = true")
            .HasDatabaseName("ux_engineer_assignments_schedule_active");
    }
}
