using Ashraak.Cctv.Service.Domain.Aggregates.Schedule.Events;
using Ashraak.Cctv.Service.Domain.Enums;
using Ashraak.SharedKernel.Domain.Primitives;

namespace Ashraak.Cctv.Service.Domain.Aggregates.Schedule;

/// <summary>Service schedule aggregate root (schema <c>cctv_service.service_schedules</c>).</summary>
public sealed class ServiceSchedule : AggregateRoot<ServiceScheduleId>
{
    private const int MinRescheduleReasonLength = 10;

    private readonly List<EngineerAssignment> _assignments = [];

    private ServiceSchedule(ServiceScheduleId id) : base(id) { }

    public string ScheduleNumber { get; private set; } = string.Empty;
    public Guid? AmcContractTermId { get; private set; }
    public Guid SiteId { get; private set; }
    public DateOnly ScheduledDate { get; private set; }
    public int SequenceInTerm { get; private set; }
    public ScheduleStatus Status { get; private set; }
    public DateOnly? RescheduledFrom { get; private set; }
    public bool IsAutoGenerated { get; private set; }
    public DateTime CreatedAtUtc { get; private set; }
    public Guid CreatedBy { get; private set; }
    public DateTime? UpdatedAtUtc { get; private set; }
    public Guid? UpdatedBy { get; private set; }
    public uint RowVersion { get; private set; }

    public IReadOnlyList<EngineerAssignment> Assignments => _assignments.AsReadOnly();

    public EngineerAssignment? ActiveAssignment =>
        _assignments.FirstOrDefault(a => a.IsActive);

    public static ServiceSchedule CreateAutoGenerated(
        ServiceScheduleId id,
        string scheduleNumber,
        Guid amcContractTermId,
        Guid siteId,
        DateOnly scheduledDate,
        int sequenceInTerm,
        Guid createdBy)
    {
        var schedule = new ServiceSchedule(id)
        {
            ScheduleNumber = scheduleNumber,
            AmcContractTermId = amcContractTermId,
            SiteId = siteId,
            ScheduledDate = scheduledDate,
            SequenceInTerm = sequenceInTerm,
            Status = ScheduleStatus.Planned,
            IsAutoGenerated = true,
            CreatedAtUtc = DateTime.UtcNow,
            CreatedBy = createdBy,
            RowVersion = 1
        };

        schedule.RaiseDomainEvent(new VisitScheduledDomainEvent(
            id.Value, scheduleNumber, siteId, scheduledDate, createdBy));

        return schedule;
    }

    public static ServiceSchedule CreateAdHoc(
        ServiceScheduleId id,
        string scheduleNumber,
        Guid amcContractTermId,
        Guid siteId,
        DateOnly scheduledDate,
        Guid createdBy)
    {
        var schedule = new ServiceSchedule(id)
        {
            ScheduleNumber = scheduleNumber,
            AmcContractTermId = amcContractTermId,
            SiteId = siteId,
            ScheduledDate = scheduledDate,
            SequenceInTerm = 0,
            Status = ScheduleStatus.Planned,
            IsAutoGenerated = false,
            CreatedAtUtc = DateTime.UtcNow,
            CreatedBy = createdBy,
            RowVersion = 1
        };

        schedule.RaiseDomainEvent(new VisitScheduledDomainEvent(
            id.Value, scheduleNumber, siteId, scheduledDate, createdBy));

        return schedule;
    }

    public void AssignEngineer(Guid engineerId, Guid assignedBy)
    {
        EnsureNotTerminal();

        if (Status is ScheduleStatus.InProgress or ScheduleStatus.Completed)
            throw new InvalidOperationException("Cannot assign engineer to a schedule that is in progress or completed.");

        var current = ActiveAssignment;
        if (current is not null)
        {
            if (current.EngineerId == engineerId)
                return;

            current.Deactivate();
            RaiseDomainEvent(new EngineerReassignedDomainEvent(
                Id.Value, current.EngineerId, engineerId, assignedBy));
        }
        else
        {
            RaiseDomainEvent(new EngineerAssignedDomainEvent(Id.Value, engineerId, assignedBy));
        }

        _assignments.Add(EngineerAssignment.Create(Id, engineerId, assignedBy));
        Status = ScheduleStatus.Assigned;
        Touch(assignedBy);
    }

    public void Reschedule(DateOnly newDate, string reason, Guid updatedBy)
    {
        EnsureNotTerminal();

        if (string.IsNullOrWhiteSpace(reason) || reason.Trim().Length < MinRescheduleReasonLength)
            throw new InvalidOperationException($"Reschedule reason must be at least {MinRescheduleReasonLength} characters.");

        if (newDate == ScheduledDate)
            throw new InvalidOperationException("New scheduled date must differ from the current date.");

        var previousDate = ScheduledDate;
        RescheduledFrom = previousDate;
        ScheduledDate = newDate;
        Touch(updatedBy);

        RaiseDomainEvent(new VisitRescheduledDomainEvent(
            Id.Value, ScheduleNumber, previousDate, newDate, updatedBy));
    }

    public void Cancel(string reason, Guid updatedBy)
    {
        EnsureNotTerminal();

        if (string.IsNullOrWhiteSpace(reason))
            throw new InvalidOperationException("Cancel reason is required.");

        Status = ScheduleStatus.Cancelled;
        Touch(updatedBy);

        RaiseDomainEvent(new VisitCancelledDomainEvent(Id.Value, ScheduleNumber, reason.Trim(), updatedBy));
    }

    public void MarkInProgress(Guid updatedBy)
    {
        if (ActiveAssignment is null)
            throw new InvalidOperationException("An engineer must be assigned before the schedule can start.");

        if (Status is not ScheduleStatus.Assigned and not ScheduleStatus.Planned)
            throw new InvalidOperationException($"Cannot start schedule in status {Status}.");

        Status = ScheduleStatus.InProgress;
        Touch(updatedBy);
    }

    public void MarkCompleted(Guid updatedBy)
    {
        if (Status is not ScheduleStatus.InProgress)
            throw new InvalidOperationException("Only in-progress schedules can be completed.");

        Status = ScheduleStatus.Completed;
        Touch(updatedBy);
    }

    public void MarkMissed(Guid updatedBy)
    {
        if (Status is ScheduleStatus.Completed or ScheduleStatus.Cancelled)
            throw new InvalidOperationException("Completed or cancelled schedules cannot be marked missed.");

        Status = ScheduleStatus.Missed;
        Touch(updatedBy);

        RaiseDomainEvent(new VisitMissedDomainEvent(Id.Value, ScheduleNumber, updatedBy));
    }

    private void EnsureNotTerminal()
    {
        if (Status is ScheduleStatus.Completed or ScheduleStatus.Cancelled or ScheduleStatus.Missed)
            throw new InvalidOperationException($"Schedule in status {Status} cannot be modified.");
    }

    private void Touch(Guid updatedBy)
    {
        UpdatedAtUtc = DateTime.UtcNow;
        UpdatedBy = updatedBy;
        RowVersion++;
    }
}
